import './globals.scss';

import classNames from 'classnames';
import type { Metadata } from 'next';
import { Raleway, Roboto } from 'next/font/google';
import { ReactNode } from 'react';

import Footer from '@/layouts/Footer';
import Header from '@/layouts/Header';

export const metadata: Metadata = {
  title: 'WebStudio',
  description: 'Generated by create next app',
};

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--fontRaleway',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
  display: 'swap',
  variable: '--fontRoboto',
});

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={classNames('layoutCss', roboto.variable, raleway.variable)}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
